---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gavinnewsom-redis
  namespace: spoke-rewired
  labels:
    app: gavinnewsom-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gavinnewsom-redis
  template:
    metadata:
      labels:
        app: gavinnewsom-redis
    spec:
      containers:
        - name: master
          image: redis:6.2.7
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
