---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gavinnewsom-shortie
  namespace: spoke-rewired
  labels:
    app: gavinnewsom-shortie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gavinnewsom-shortie
  template:
    metadata:
      labels:
        app: gavinnewsom-shortie
    spec:
      containers:
        - name: fly-shortener
          image: us-east4-docker.pkg.dev/assemble-services/apps/link-shortener:1.3.2
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_FAMILY
              value: "6"
            - name: REDIS_USERNAME
              value: "default"
            - name: SOURCE
              value: google-sheets
            - name: GOOGLE_SHEET_RANGE
              value: "'Live Links'!B2:D"
            - name: GOOGLE_SERVICE_ACCOUNT_EMAIL
              value: short-links@my-project.iam.gserviceaccount.com
            - name: GOOGLE_SERVICE_ACCOUNT_KEY
              value: "SECRET"
            - name: AIRTABLE_API_KEY
              value: ignore
            - name: AIRTABLE_BASE
              value: ignore
            - name: ADMIN_SECRET
              value: jaYsDPHdq8kolL7h9sZ45HobUikHVCdJ
            - name: FALLBACK_URL
              value: https://www.gavinnewsom.com/
            - name: TIMEZONE
              value: America/Los_Angeles
            - name: REDIS_HOST
              value: "gavinnewsom-redis"
            - name: REDIS_PASSWORD
              value: "SECRET"
            - name: GOOGLE_SHEET_DOC_ID
              value: SECRET
